name: Build and Deploy Capacitor App

on:
  workflow_dispatch:

jobs:
  android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Sync Capacitor for Android
        run: npx cap sync android

      - name: Build Android App
        working-directory: android
        run: |
          ./gradlew assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk

  ios:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Sync Capacitor for iOS
        run: npx cap sync ios

      - name: Build iOS App Archive
        working-directory: ios/App
        run: |
          xcodebuild -scheme App -configuration Release -sdk iphoneos archive -archivePath App.xcarchive

      - name: Export iOS IPA
        working-directory: ios/App
        run: |
          xcodebuild -exportArchive -archivePath App.xcarchive -exportOptionsPlist ../exportOptions.plist -exportPath ./build

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: ios/App/build/App.ipa
