name: Build and Deploy Capacitor App

on:
  workflow_dispatch:
  
jobs:
  android:
    name: Build Android APK
    runs-on: ubuntu-latest
    env:
      CI: false  # if needed to not fail on warnings
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Dependencies
        working-directory: sourceCode/shopping-list-app
        run: npm install

      - name: Build Web App
        working-directory: sourceCode/shopping-list-app
        run: npm run build

      # Copy assets to native projects
      - name: Copy Capacitor Assets
        working-directory: sourceCode/shopping-list-app
        run: npx cap copy

      - name: Sync Capacitor for Android
        working-directory: sourceCode/shopping-list-app
        run: npx cap sync android

      - name: Set gradlew permissions
        working-directory: sourceCode/shopping-list-app/android
        run: chmod +x gradlew

      # If you're not signing the app, you might only have a debug build:
      - name: Build Android App (Debug)
        working-directory: sourceCode/shopping-list-app/android
        run: ./gradlew assembleDebug

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: sourceCode/shopping-list-app/android/app/build/outputs/apk/debug/app-debug.apk

  # ios:
  #   name: Build iOS IPA
  #   runs-on: macos-latest
  #   env:
  #     CI: false
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '20'

  #     - name: Install Dependencies
  #       working-directory: sourceCode/shopping-list-app
  #       run: npm install

  #     - name: Build Web App
  #       working-directory: sourceCode/shopping-list-app
  #       run: npm run build

  #     - name: Sync Capacitor for iOS
  #       working-directory: sourceCode/shopping-list-app
  #       run: npx cap sync ios

  #     - name: Build iOS App Archive
  #       working-directory: sourceCode/shopping-list-app/ios/App
  #       run: |
  #         xcodebuild -scheme App -configuration Release -sdk iphoneos archive -archivePath App.xcarchive

  #     - name: Export iOS IPA
  #       working-directory: sourceCode/shopping-list-app/ios/App
  #       run: |
  #         xcodebuild -exportArchive -archivePath App.xcarchive -exportOptionsPlist ../exportOptions.plist -exportPath ./build

  #     - name: Upload iOS IPA
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ios-ipa
  #         path: sourceCode/shopping-list-app/ios/App/build/App.ipa
